### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by suddenrushofsushi** [vic/indifferent#1]
Hey there, I'm using this library in production and have some ideas for enhancements. I'd be happy to take over as maintainer.
The twitter account listed in the badge is no longer active, thus the issue here.

**Comment by vic** [comment]
Hey @suddenrushofsushi, sure.  I also have some clients that are likely using this in production.  I'm willing to make you a contributor when your first PR is merged. Could you please open a new pull-request for those enhancements so we can talk about them ?

I'm closing this issue.
